### ISSUE TITLE
Small Error

### ISSUE THREAD

**Issue by The-Don-Himself** [Happyr/CloudFlareBundle#2]
$def = $container->getDefinition('happyr.clourflare.service.cloudflare');

should be

$def = $container->getDefinition('happyr.cloudflare.service.cloudflare');

I don't know how to launch a PR but I have been using this bundle for a few days now and it seems to work, however, this very small error would crash a site upon composer install.

**Comment by skylord123** [comment]
Issue still exists. Please fix this.

**Comment by gpenverne** [comment]
Issue still exists. Please fix this. ;)

**Comment by Nyholm** [comment]
Check out the latest commit. This will solve the issue, right?

**Comment by gpenverne** [comment]
Right! Thanks!

**Comment by The-Don-Himself** [comment]
@Nyholm I just did a composer install today and this issue still exists. Please note that because of this small error, any post install scripts do not run causing a lot of havoc.

**Comment by Nyholm** [comment]
What version did you install?

**Comment by The-Don-Himself** [comment]
Should be the latest, this is what I have in my composer json

```
        "happyr/cloud-flare-bundle": "^0.2.0",
```

**Comment by The-Don-Himself** [comment]
Results from composer show -i

```
happyr/cloud-flare-bundle              0.2.0              This Symfony2 bundle lets you talk to the CloudFlare client API
```

**Comment by Nyholm** [comment]
Make sure to install the 0.2.1 version. That will include this fix.

**Comment by The-Don-Himself** [comment]
Changed my composer.json to >0.2.0 then ^0.2.1 then ~0.2.1 all have refused to download version 0.2.1. Have you tried on your end, I clear my composer cache. The error brought about on each occasion is 

```
> cd /var/www composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package happyr/cloud-flare-bundle could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

**Comment by Nyholm** [comment]
Sorry packagist autoupdate was not properly configured. See https://packagist.org/packages/happyr/cloud-flare-bundle

0.2.1 does exist now.

**Comment by The-Don-Himself** [comment]
:+1: 
Its worked now... thanks!
